service: aws-crud-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:875564387106:table/EmployeeTable

functions:
  getEmployee:
    handler: src/getEmployee.getEmployee
    events:
      - httpApi:
          path: /{id}
          method: get
  listEmployee:
    handler: src/listEmployee.listEmployee
    events:
      - httpApi:
          path: /list
          method: get
  createEmployee:
    handler: src/addEmployee.addEmployee
    events:
      - httpApi:
          path: /create
          method: post
 
  updateEmployee:
    handler: src/updateEmployee.updateEmployee
    events:
      - httpApi:
          path: /update
          method: put
  
  deleteEmployee:
    handler: src/deleteEmployee.deleteEmployee
    events:
      - httpApi:
          path: /{id}
          method: delete

resources:
  Resources:
    EmployeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: EmployeeTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH